server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=medapp_db;encrypt=false
    username: medapp_auth
    password: medapppassword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database: mssql
    database-platform: org.hibernate.dialect.SQLServerDialect
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
