
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=medapp_db;encrypt=false
    username: medapp_auth
    password: medapppassword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database: mssql
    database-platform: org.hibernate.dialect.SQLServerDialect
